### ISSUE TITLE
zerodb-manage init_db error

### ISSUE THREAD

**Issue by jagjag** [zero-db/zerodb#41]
```
Username [root]: root
Passphrase: 
Repeat for confirmation: 
Sock [localhost:8001]: localhost:8002
Traceback (most recent call last):
  File "/bin/zerodb-manage", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/zerodbext/server/manage.py", line 67, in auth_func
    ctx.invoke(f, *args, **kw)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/zerodbext/server/manage.py", line 148, in init_db
    key = ecc.private(_passphrase).get_pubkey()
  File "/usr/lib/python2.7/site-packages/zerodb/crypto/ecc.py", line 35, in private
    key = pe.ECC(curve=CURVE)
  File "/usr/lib/python2.7/site-packages/pyelliptic/ecc.py", line 89, in __init__
    self.privkey, self.pubkey_x, self.pubkey_y = self._generate()
  File "/usr/lib/python2.7/site-packages/pyelliptic/ecc.py", line 223, in _generate
    raise Exception("[OpenSSL] EC_KEY_generate_key FAIL ... " + OpenSSL.get_error())
Exception: [OpenSSL] EC_KEY_generate_key FAIL ... error:100AE081:elliptic curve routines:EC_GROUP_new_by_curve_name:unknown group
```

**Comment by jagjag** [comment]
RHEL 7.1  

python
Python 2.7.5 (default, Oct 11 2015, 17:47:16) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2

openssl-1.0.1e-51.el7_2.4.x86_64

**Comment by michwill** [comment]
Seems like the issue here is that OpenSSL in RH doesn't have curve secp256k1.
There are multiple non-mutually-exclusive fixes possible here.

- Use [pure-python fallback](https://github.com/vbuterin/pybitcointools/blob/master/bitcoin/main.py) for this curve as a fallback;
- Specify curve name (some people may want to use NIST curves?);
- Perform a planned switch to D. Bernstein's Curve25519 or Curve41417 (using libsodium as an implementation?)

**Comment by michwill** [comment]
Now using ECDSA library independent on OpenSSL. Should work in RH
